### PR TITLE
[BugFix] Fix compilation error in branch-4.1 backport of #68434

### PR DESCRIPTION
**Pull request by wxl24life**
## Why I'm doing this

The backport PR #72079 has a CI compilation failure:

```
ERROR /root/starrocks/fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:[658,13] cannot find symbol
  symbol:   method putPartitionToRecycleBin(com.starrocks.catalog.RecyclePartitionInfo)
```

`putPartitionToRecycleBin` was introduced by PR #71425 which only landed in `main`, not `branch-4.1`. The backport of #68434 accidentally referenced this helper.

## What I'm doing

Replace the call to `putPartitionToRecycleBin(recyclePartitionInfo)` with the equivalent direct call `idToPartition.put(partitionId, recyclePartitionInfo)` that works in branch-4.1.

## Type

- [x] BugFix

### CODE REVIEW

**Comment by wxl24life** [comment]
@mergify auto merge

**Comment by wxl24life** [comment]
@mergify automerge
