### PR TITLE
fix compile failure due to not founding jni.h

### PR DESCRIPTION
**Pull request by rzuo**
When compiling be, it failed with following message:

[ 12%] Building CXX object src/exprs/CMakeFiles/Exprs.dir/vectorized/java_function_call_expr.cpp.o
/home/rzuo/tmp/starrocks/be/src/exprs/vectorized/java_function_call_expr.cpp:27:10: fatal error: jni.h: No such file or directory
   27 | #include "jni.h"
      |          ^~~~~~~
compilation terminated.
make[2]: *** [src/exprs/CMakeFiles/Exprs.dir/build.make:641: src/exprs/CMakeFiles/Exprs.dir/vectorized/java_function_call_expr.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:823: src/exprs/CMakeFiles/Exprs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Built target Exec
make: *** [Makefile:171: all] Error 2

### CODE REVIEW

**Comment by rzuo** [comment]
bad commit, close this PR.
