### ISSUE TITLE
The server does not support the AVX2 instruction set,

### ISSUE THREAD

**Issue by liubotao** [StarRocks/starrocks#52658]
### Steps to reproduce the behavior (Required)

The server does not support the AVX2 instruction set, causing the compilation to fail. Compilation was previously successful, but after merging the latest changes from the main branch, it now fails.

```
./build.sh --be
```
```
/project/starrocks/be/src/util/bit_packing_adapter.h:101:2: 错误：#error "Not supported instruction set"
  101 | #error "Not supported instruction set"
```

### Expected behavior (Required)

BE compiled successfully

### Real behavior (Required)

BE compilation failed

### StarRocks version (Required)

main branch

**Comment by kevincai** [comment]
introduced in https://github.com/StarRocks/starrocks/pull/50904
