### ISSUE TITLE
Fail to compile BE with the option --use-staros

### ISSUE THREAD

**Issue by sduzh** [StarRocks/starrocks#12863]
### Steps to reproduce the behavior (Required)
1. ./build.sh --be --clean --use-staros

### Expected behavior (Required)
Build success

### Real behavior (Required)
```
FAILED: src/common/CMakeFiles/Common.dir/logconfig.cpp.o
ccache /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/bin/g++  -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DUSE_JEMALLOC -I../src/formats/orc/apache-orc/c++/include -I/home/disk1/zhuming/starlet-installed/third_party/include -I/home/disk1/zhuming/starlet-installed/starlet_install/include -I../src -I../test -I../../gensrc/build -I/home/disk3/sr-deps/thirdparty/installed/include/breakpad -I/home/disk3/sr-deps/thirdparty/installed/open_jdk/include -I/home/disk3/sr-deps/thirdparty/installed/open_jdk/include/linux -isystem /home/disk3/sr-deps/thirdparty/installed/include -isystem /home/disk3/sr-deps/thirdparty/installed/gperftools/include -isystem /home/disk3/sr-deps/thirdparty/installed/include/thrift -isystem /home/disk3/sr-deps/thirdparty/installed/include/event -Wall -Wno-sign-compare -Wno-unknown-pragmas -pthread -Wno-register -Wno-strict-aliasing -fno-omit-frame-pointer -std=gnu++17 -D__STDC_FORMAT_MACROS -Wno-deprecated -Wno-vla -Wno-comment -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -Werror=return-type -Werror=switch -DUSE_STAROS -msse4.2 -mavx2  -Wno-attributes -DS2_USE_GFLAGS -DS2_USE_GLOG -faligned-new -gz=zlib  -Werror -g -Wno-unused-local-typedefs -O3 -gdwarf-4 -DNDEBUG -O3 -DNDEBUG -MD -MT src/common/CMakeFiles/Common.dir/logconfig.cpp.o -MF src/common/CMakeFiles/Common.dir/logconfig.cpp.o.d -o src/common/CMakeFiles/Common.dir/logconfig.cpp.o -c ../src/common/logconfig.cpp
../src/common/logconfig.cpp: In function ‘bool starrocks::init_glog(const char*, bool)’:
../src/common/logconfig.cpp:126:5: error: ‘FLAGS_log_filenum_quota’ was not declared in this scope
  126 |     FLAGS_log_filenum_quota = config::sys_log_roll_num;
      |     ^~~~~~~~~~~~~~~~~~~~~~~
../src/common/logconfig.cpp:156:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  156 |         FLAGS_log_split_method = "day";
      |         ^~~~~~~~~~~~~~~~~~~~~~
../src/common/logconfig.cpp:159:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  159 |         FLAGS_log_split_method = "hour";
      |         ^~~~~~~~~~~~~~~~~~~~~~
../src/common/logconfig.cpp:162:9: error: ‘FLAGS_log_split_method’ was not declared in this scope
  162 |         FLAGS_log_split_method = "size";
      |         ^~~~~~~~~~~~~~~~~~~~~~
[11/950] Building CXX object src/agent/CMakeFiles/Agent.dir/report_task.cpp.o
```

### StarRocks version (Required)
 - main branch a5bb5e70ae3216493896ea6a28c0cefbd67cfcff

**Comment by sduzh** [comment]
Introduced by 0fbf4998.
