### ISSUE TITLE
Run build.sh failed in dev-env Docker container due to brpc glog update in #48949

### ISSUE THREAD

**Issue by jiangyinzuo** [StarRocks/starrocks#49172]
### Steps to reproduce the behavior (Required)
1. `docker pull starrocks/dev-env-ubuntu:latest`
2.  Create a docker container and enter.
3.  run `./build.sh` in docker

### Expected behavior (Required)

Build successfully

### Real behavior (Required)

Build failed
```
/data/starrocks/be/src/common/logconfig.cpp: In function ‘bool starrocks::init_glog(const char*, bool)’:
/data/starrocks/be/src/common/logconfig.cpp:280:38: error: invalid conversion from ‘void (*)(const char*, size_t)’ {aka ‘void (*)(const char*, long unsigned int)’} to ‘void (*)(const char*, int)’ [-fpermissive]
  280 |         google::InstallFailureWriter(failure_writer);
      |                                      ^~~~~~~~~~~~~~
      |                                      |
      |                                      void (*)(const char*, size_t) {aka void (*)(const char*, long unsigned int)}
In file included from /data/starrocks/be/src/common/logconfig.cpp:18:
/var/local/thirdparty/installed/include/glog/logging.h:1663:12: note:   initializing argument 1 of ‘void google::InstallFailureWriter(void (*)(const char*, int))’
 1663 |     void (*writer)(const char* data, int size));
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/starrocks/be/src/common/logconfig.cpp:281:49: error: ‘logging_fail_func_t’ is not a member of ‘google’
  281 |         google::InstallFailureFunction((google::logging_fail_func_t)failure_function);
      |                                                 ^~~~~~~~~~~~~~~~~~~
/data/starrocks/be/src/common/logconfig.cpp: At global scope:
/data/starrocks/be/src/common/logconfig.cpp:175:13: warning: ‘void starrocks::failure_function()’ defined but not used [-Wunused-function]
  175 | static void failure_function() {
      |             ^~~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/Common.dir/build.make:132: src/common/CMakeFiles/Common.dir/logconfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:669: src/common/CMakeFiles/Common.dir/all] Error 2
```
### StarRocks version (Required)
main branch (576c8147212c9c3d5ab5125cba4c5b3c011240bb)

### Possible Solution

#48949 updated [be/src/common/logconfig.cpp](https://github.com/StarRocks/starrocks/pull/48949/files#diff-a66e3e8dde0349940e4a43541577d6a622d30fff1d6718b7e79b87d54b06e188), changed `logconfig.cpp:281` to `google::InstallFailureFunction((google::logging_fail_func_t)failure_function);`, but only glog v0.7.1 has type `google::logging_fail_func_t`. So Docker environment with glog v0.3.3 and v0.4.0 may build failed.

Should we need to update `thirdparty_url` in `dev-env.Dockerfile` ?
https://github.com/StarRocks/starrocks/blob/0f639ad566594c390fd9a8dc1c99c4e72ffdd103/docker/dockerfiles/dev-env/dev-env.Dockerfile#L22

**Comment by kevincai** [comment]
do check the dev-env-ubuntu version from dockerhub. it will be some time delay after the code is checked in

https://hub.docker.com/layers/starrocks/dev-env-ubuntu/latest/images/sha256-bf190589d0daa67166c612d397af24c6d1c9f8d87c23be1f158cfa3b1dce9105?context=explore
