### PR TITLE
fix ut compile error

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Problem Summary(Required) ：

Fix ut compile error by earlier PR

### CODE REVIEW

**Comment by decster** [comment]
```
18:22:46 /root/starrocks/be/test/storage/task/engine_storage_migration_task_test.cpp:25:10: fatal error: storage/vectorized/chunk_helper.h: No such file or directory
18:22:46    25 | #include "storage/vectorized/chunk_helper.h"
```
Caused by #4939 & #4857

**Review by wyb — APPROVED** [review]

**Review by imay — APPROVED** [review]
