### PR TITLE
[BugFix] Fix benchmark compilation errors

### LINKED ISSUE #67414: benchmark compile error
### Steps to reproduce the behavior (Required)
benchmark compile error 
```
[100%] Built target orc_column_reader_bench
In file included from /root/starrocks/be/src/common/cow.h:23,
                 from /root/starrocks/be/src/column/column.h:26,
                 from /root/starrocks/be/src/column/const_column.h:17,
                 from /root/starrocks/be/src/column/column_helper.h:22,
                 from /root/starrocks/be/src/bench/get_dict_codes_bench.cpp:20:
/root/starrocks/be/src/gutil/casts.h: In instantiation of ‘To down_cast(From*) [with To = starrocks::BinaryColumnBase<unsigned int>*; From = const starrocks::Column]’:
/root/starrocks/be/src/bench/get_dict_codes_bench.cpp:89:66:   required from here
   89 |         auto* dict_value_binary_column = down_cast<BinaryColumn*>(dict_nullable_column->data_column().get());
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/starrocks/be/src/gutil/casts.h:80:12: error: ‘static_cast’ from type ‘const starrocks::Column*’ to type ‘starrocks::BinaryColumnBase<unsigned int>*’ casts away qualifiers
   80 |     return static_cast<To>(f);
      |            ^~~~~~~~~~~~~~~~~~
make[2]: *** [src/bench/CMakeFiles/get_dict_codes_bench.dir/build.make:79: src/bench/CMakeFiles/get_dict_codes_bench.dir/get_dict_codes_bench.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2383: src/bench/CMakeFiles/get_dict_codes_bench.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

/root/starrocks/be/src/bench/hash_functions_bench.cpp: In member function ‘void starrocks::HourFromUnixtimeBench::bench_from_unixtime_extract_hour(benchmark::State&)’:
/root/starrocks/be/src/bench/hash_functions_bench.cpp:247:47: error: ‘class starrocks::Column’ has no member named ‘get_data’
  247 |                 dt_col->as_mutable_raw_ptr()->get_data()[i].to_timestamp(&year, &month, &day, &hour, &minute, &second,
      |                                               ^~~~~~~~
make[2]: *** [src/bench/CMakeFiles/hash_functions_bench.dir/build.make:79: src/bench/CMakeFiles/hash_functions_bench.dir/hash_functions_bench.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2563: src/bench/CMakeFiles/hash_functions_bench.dir/all] Error 2
/root/starrocks/be/src/bench/object_cache_bench.cpp: In member function ‘void starrocks::ObjectCacheBench::init_cache(starrocks::CacheType)’:
/root/starrocks/be/src/bench/object_cache_bench.cpp:123:38: error: cannot convert ‘starrocks::DiskCacheOptions’ to ‘const starrocks::MemCacheOptions&’
  123 |         Status st = _lru_cache->init(opt);
      |                                      ^~~
      |                                      |
      |                                      starrocks::DiskCacheOptions
In file included from /root/starrocks/be/src/bench/object_cache_bench.cpp:22:
/root/starrocks/be/src/cache/mem_cache/lrucache_engine.h:28:40: note:   initializing argument 1 of ‘starrocks::Status starrocks::LRUCacheEngine::init(const starrocks::MemCacheOptions&)’
   28 |     Status init(const MemCacheOptions& options);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/root/starrocks/be/src/bench/object_cache_bench.cpp:137:42: error: cannot convert ‘std::__shared_ptr<starrocks::StarCacheEngine, __gnu_cxx::_S_atomic>::element_type*’ {aka ‘starrocks::StarCacheEngine*’} to ‘starrocks::LocalMemCacheEngine*’
  137 |         _page_cache->init(_star_cache.get());
      |                           ~~~~~~~~~~~~~~~^~
      |                                          |
      |                                          std::__shared_ptr<starrocks::StarCacheEngine, __gnu_cxx::_S_atomic>::element_type* {aka starrocks::StarCacheEngine*}
In file included from /root/starrocks/be/src/bench/object_cache_bench.cpp:23:
/root/starrocks/be/src/cache/mem_cache/page_cache.h:71:36: note:   initializing argument 1 of ‘void starrocks::StoragePageCache::init(starrocks::LocalMemCacheEngine*)’
   71 |     void init(LocalMemCacheEngine* cache_engine) {
      |               ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
make[2]: *** [src/bench/CMakeFiles/object_cache_bench.dir/build.make:79: src/bench/CMakeFiles/object_cache_bench.dir/object_cache_bench.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2983: src/bench/CMakeFiles/object_cache_bench.dir/all] Error 2
In file included from /opt/gcc-toolset-14/include/c++/14.3.0/bits/stl_iterator.h:78,
                 from /opt/gcc-toolset-14/include/c++/14.3.0/bits/stl_algobase.h:67,
                 from /opt/gcc-toolset-14/include/c++/14.3.0/algorithm:60,
                 from /var/local/thirdparty/installed/include/benchmark/benchmark.h:179,
                 from /root/starrocks/be/src/bench/chunks_sorter_bench.cpp:15:
/opt/gcc-toolset-14/include/c++/14.3.0/bits/stl_construct.h: In instantiation of ‘constexpr void std::_Construct(_Tp*, _Args&& ...) [with _Tp = starrocks::Chunk; _Args = {vector<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column>, allocator<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column> > >&, phmap::flat_hash_map<int, long unsigned int, starrocks::StdHash<int>, phmap::EqualTo<int>, allocator<pair<const int, long unsigned int> > >&}]’:
/opt/gcc-toolset-14/include/c++/14.3.0/bits/alloc_traits.h:706:19:   required from ‘static constexpr void std::allocator_traits<std::allocator<void> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = starrocks::Chunk; _Args = {std::vector<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column>, std::allocator<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column> > >&, phmap::flat_hash_map<int, long unsigned int, starrocks::StdHash<int>, phmap::EqualTo<int>, std::allocator<std::pair<const int, long unsigned int> > >&}; allocator_type = std::allocator<void>]’
  706 |         { std::_Construct(__p, std::forward<_Args>(__args)...); }
      |           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/gcc-toolset-14/include/c++/14.3.0/bits/shared_ptr_base.h:607:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::vector<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column>, std::allocator<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column> > >&, phmap::flat_hash_map<int, long unsigned int, starrocks::StdHash<int>, phmap::EqualTo<int>, std::allocator<std::pair<const int, long unsigned int> > >&}; _Tp = starrocks::Chunk; _Alloc = std::allocator<void>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
  607 |           allocator_traits<_Alloc>::construct(__a, _M_ptr(),
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  608 |               std::forward<_Args>(__args)...); // might throw
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
/opt/gcc-toolset-14/include/c++/14.3.0/bits/shared_ptr_base.h:969:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = starrocks::Chunk; _Alloc = std::allocator<void>; _Args = {std::vector<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column>, std::allocator<starrocks::Cow<starrocks::Column>::ImmutPtr<starrocks::Column> > >&, phmap::flat_hash_map<int, long unsigned int, starrocks::StdHash<int>, phmap::EqualTo<int>, std::allocator<std::pair<const int, long unsigned int> > >&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
  969 |           auto __pi = ::new (__mem)
      |                       ^~~~~~~~~~~~~
  970 |             _Sp_cp_type(__a._M_a, std::forward<_Args>(__args)...);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by arvindKandpal-ksolves**
Fixed compilation issues in benchmark files due to API changes:
- chunks_sorter_bench.cpp: Updated Chunk constructor usage.
- get_dict_codes_bench.cpp: Fixed const correctness in down_cast.
- hash_functions_bench.cpp: Fixed Column downcast to TimestampColumn.
- object_cache_bench.cpp: Updated LRUCacheEngine init and disabled incompatible StarCache path.

## Why I'm doing:

The benchmark files under `be/src/bench/` were failing to compile due to recent API changes in the core backend. This PR fixes the compilation errors to allow benchmarks to run successfully.

## What I'm doing:

- Updated `chunks_sorter_bench.cpp` to use the correct `Chunk` constructor signature (removed deprecated map argument).
- Fixed `get_dict_codes_bench.cpp` by adding `const` to `down_cast` to match the source pointer type.
- Updated `hash_functions_bench.cpp` to correctly downcast generic `Column` pointers to `TimestampColumn` before accessing `get_data()`.
- Modified `object_cache_bench.cpp` to initialize `LRUCacheEngine` with `MemCacheOptions` instead of `DiskCacheOptions`.
- Temporarily disabled the `StarCacheEngine` path in `object_cache_bench.cpp` as it is currently incompatible with `StoragePageCache`.

Fixes #67414

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function
- [ ] This pr needs auto generate documentation
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 4.0
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> Aligns benchmark code with recent API changes and expands cache benchmarking.
> 
> - Update `chunks_sorter_bench.cpp` to construct `Chunk` with `std::move(columns)` across usages
> - Fix const-correct casts in `get_dict_codes_bench.cpp` (`down_cast<const BinaryColumn*>`)
> - Correct `hash_functions_bench.cpp` to read `TimestampColumn` via `down_cast<const TimestampColumn*>` and `get_data()`
> - Refactor `object_cache_bench.cpp`:
>   - Initialize `LRUCacheEngine` with `MemCacheOptions`
>   - Introduce `BlockCache` path with `StarCacheEngine`; add prepare/query/insert (single/multi-thread) helpers for BlockCache
>   - Branch metrics/logging and multi-thread flows based on cache type
> - Adjust `orc_column_reader_bench.cpp` to pass `orcMapping.get()` and call `get_next(c0, column.get(), ...)`
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4886b6c81ac4c6ea08f98d348ef046f444b892a7. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alvin-celerdata** [comment]
@cursor review

**Comment by arvindKandpal-ksolves** [comment]
Hi @kevincai and @alvin-celerdata Can you re-review it and let me know if need any changes.

File: be/src/bench/chunks_sorter_bench.cpp [hunk 1]
```diff
@@ -219,9 +219,8 @@ static void do_bench(benchmark::State& state, SortAlgorithm sorter_algo, Logical
         sort_exprs.push_back(sort_expr);
         asc_arr.push_back(true);
         null_first.push_back(true);
-        map[i] = i;
     }
-    auto chunk = std::make_shared<Chunk>(columns, map);
+    auto chunk = std::make_shared<Chunk>(columns, Chunk::SlotHashMap{});
```
Comment (kevincai) [inline be/src/bench/chunks_sorter_bench.cpp]: This is not right. the compiling failure because of the Chunk contructor now requires a `Columns&&` as its contructor parameter.

```suggestion
    auto chunk = std::make_shared<Chunk>(std::move(columns), map);
```

File: be/src/bench/hash_functions_bench.cpp [hunk 2]
```diff
@@ -241,11 +241,13 @@ class HourFromUnixtimeBench {
             auto dt_col_ptr = starrocks::TimeFunctions::from_unix_to_datetime_64(utils->get_fn_ctx(), columns).value();
             auto dt_col = starrocks::ColumnHelper::cast_to<starrocks::TYPE_DATETIME>(dt_col_ptr);
             int64_t sum = 0;
-            // Use const_cast for read-only benchmark access
+
+            auto* timestamp_col = down_cast<TimestampColumn*>(dt_col.get());
```
Comment (kevincai) [inline be/src/bench/hash_functions_bench.cpp]: this is not compilable.

```
be/src/gutil/casts.h:80:12: error: static_cast from 'const starrocks::FixedLengthColumn<starrocks::TimestampValue> *' to 'starrocks::FixedLengthColumn<starrocks::TimestampValue> *', which are not related by inheritance, is not allowed
    return static_cast<To>(f);
           ^~~~~~~~~~~~~~~~~~
be/src/bench/hash_functions_bench.cpp:245:35: note: in instantiation of function template specialization 'down_cast<starrocks::FixedLengthColumn<starrocks::TimestampValue> *, const starrocks::FixedLengthColumn<starrocks::TimestampValue>>' requested here
            auto* timestamp_col = down_cast<TimestampColumn*>(dt_col.get());
                                  ^
1 error generated.

```

File: be/src/bench/object_cache_bench.cpp [hunk 3]
```diff
@@ -134,8 +136,8 @@ void ObjectCacheBench::init_cache(CacheType cache_type) {
             LOG(FATAL) << "init star cache failed: " << st;
         }
         _page_cache = std::make_shared<StoragePageCache>();
-        _page_cache->init(_star_cache.get());
-        LOG(INFO) << "init star cache succ";
+        // _page_cache->init(_star_cache.get());
```
Comment (kevincai) [inline be/src/bench/object_cache_bench.cpp]: The incompatibility is introduced by https://github.com/StarRocks/starrocks/pull/63734

Comment (kevincai) [reply be/src/bench/object_cache_bench.cpp]: so the bench shall be split into two difference mode: 

* CacheType::LRU -> bench for _page_cache
* CacheType::STAR -> bench for _block_cache

Please try to fix in this way instead of simply disabling it.

cc @trueeyu

**Review by kevincai — COMMENTED** [review]
Thanks for taking the initiative. Will take this bench into regular CI regression if not build every for every PR.

B.t.w., `be/src/bench/orc_column_reader_bench.cpp` is also broken, please take a look and fix it in this patch if possible.

**Review by kevincai — APPROVED** [review]

**Comment by alvin-celerdata** [comment]
@cursor review

**Review by trueeyu — APPROVED** [review]
