### ISSUE TITLE
Java NoClassDefFoundError on BE while querying Iceberg tables on Glue

### ISSUE THREAD

**Issue by mcgray** [StarRocks/starrocks#56322]
Having issues with certain queries to Iceberg tables in Glue on 3.3.9. Please see below for details. 
Tested - same queries are working on 3.2.3 on a different cluster. Other Select queries are working fine. 

### Steps to reproduce the behavior (Required)
1. SELECT count(*) FROM iceberg_glue.db_name.table_name

### Expected behavior (Required)
Show count

### Real behavior (Required)
```
SQL Error [1064] [42000]: Failed to execute metadata collection job. Failed to open the off-heap table scanner. java exception details: java.lang.NoClassDefFoundError: Could not initialize class de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer
	at com.starrocks.connector.iceberg.IcebergMetadataScanner.initSerializer(IcebergMetadataScanner.java:207)
	at com.starrocks.connector.iceberg.IcebergMetadataScanner.open(IcebergMetadataScanner.java:132)
: BE:11403
```

### StarRocks version (Required)
3.3.9

### Additional info
be.out error:
```
Exception Exception in thread "Thread-19" Exception in thread "Thread-7" Exception in thread "main" in thread "Thread-13" Exception in thread "Thread-18" Exception in thread "Thread-16" Exception in thread "Thread-17" java.lang.NoClassDefFoundError: Could not initialize class de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer
Exception       at com.starrocks.connector.iceberg.IcebergMetadataScanner.initSerializer(IcebergMetadataScanner.java:207)
in thread "Thread-11"   at com.starrocks.connector.iceberg.IcebergMetadataScanner.open(IcebergMetadataScanner.java:132)
Exception in thread "Thread-5" java.lang.ExceptionInInitializerError
        at com.starrocks.connector.iceberg.IcebergMetadataScanner.initSerializer(IcebergMetadataScanner.java:207)
        at com.starrocks.connector.iceberg.IcebergMetadataScanner.open(IcebergMetadataScanner.java:132)
Caused by: java.lang.RuntimeException: Could not access source collection field in java.util.Collections$UnmodifiableCollection.
        at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.<clinit>(UnmodifiableCollectionsSerializer.java:62)
        ... 2 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final java.util.Collection java.util.Collections$UnmodifiableCollection.c accessible: module java.base does not "opens java.util" to unnamed module @620f9f9a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer.<clinit>(UnmodifiableCollectionsSerializer.java:55)
        ... 2 more
Exception in thread "Thread-22" Exception java.lang.NoClassDefFoundError: Could not initialize class de.javakaffee.kryoserializers.UnmodifiableCollectionsSerializer
in thread "Thread-12"   at com.starrocks.connector.iceberg.IcebergMetadataScanner.initSerializer(IcebergMetadataScanner.java:207)
        at com.starrocks.connector.iceberg.IcebergMetadataScanner.open(IcebergMetadataScanner.java:132)
```
Kryo related contents of the lib folder on Backend.
```
 find . -type f -name "*kryo*"
./iceberg-reader-lib/kryo-shaded-4.0.2.jar
./iceberg-reader-lib/kryo-serializers-0.45.jar
./hudi-reader-lib/kryo-shaded-4.0.2.jar
```

**Comment by DorianZheng** [comment]
@mcgray Thanks for filing this issue. We will fix it ASAP. You can run `set global plan_mode=local` to workaround right now.

**Comment by mcgray** [comment]
Thanks, going to use this one.

**Comment by Youngwb** [comment]
@mcgray This issue is likely caused by the BE running on a higher version of Java than expected. You should check the   JAVA_HOME   environment variable for your BE. Version 3.3.9 is supposed to run on JDK 8.

**Comment by igor-raits** [comment]
We have hit this issue as well, we are using cn-ubuntu:latest container and looks like that one has JDK 17

**Comment by mcgray** [comment]
@ignatenkobrain `SET GLOBAL plan_mode="local"` works for me. Cannot say if performance is impacted since it is not trivial how to A/B test it.
